name: redstone_security_plugin
version: 0.0.1
author: Cristian Garcia <cgarcia.e88@gmail.com>
description: Redstone plugin to handle role-based authorization through cookies
homepage: https://github.com/redstone-dart/redstone-headers-plugin
environment:
  sdk: '>=1.9.1'
documentation: https://github.com/redstone-dart/redstone-headers-plugin
dependencies:
  redstone: '>=0.6.0-beta.1 < 0.7.0'
  cookies: ">=0.0.3 < 1.0.0"
